### ISSUE TITLE
Do we need atomic queue::size()?

### ISSUE THREAD

**Issue by JiakunYan** [berkeley-container-library/bcl#8]
Currently the `queue::size()` method is implemented as below
```
  size_t size() const {
    return BCL::rget(tail) - BCL::rget(head);
  }
```
When it is used simultaneously with push&pop, it might get unpredictable results.
Do we need to implement an atomic version?

**Comment by BenBrock** [comment]
My feeling is that an atomic queue::size() is not generally possible, since it would require an atomic operation that returns two integers, which is not generally available on current-generation RDMA hardware.

Even so, it's not all that clear to me how an atomic queue::size() would be used, since the queue size  you retrieved atomically may be different by the time you use it in another operation.

I generally expect queue::size() to be used non-concurrently with other queue operations, or else in a heuristic way where the exact value doesn't matter that much.
